#######################################################################################
# SUBJECT: Calculator MAKEFILE
#
# DEVELOPER: Moshe Elisha				TEAM:
#
#######################################################################################
#Variable Definitions

TDIR = ../../test
IDIR = ../../include
SDIR = ../../src
ODIR = ../../obj
OBJS = $(ODIR)/stack.o $(ODIR)/calculator_test.o $(ODIR)/calculator.o
CC = gcc -g -ansi -pedantic-errors -Wall -I $(IDIR) -lm


##########################################################################################################

all: calculator.out

##########################################################################################################
#creates an executable for avl DS

calculator.out: $(OBJS)
	$(CC) $(OBJS) -o $@

############################################################################################################
#creates object files

$(ODIR)/stack.o: $(SDIR)/stack/stack.c $(IDIR)/stack.h
	$(CC) -c $(SDIR)/stack/stack.c -o $@

$(ODIR)/calculator.o: calculator.c $(IDIR)/calculator.h
	$(CC) -c calculator.c -o $@

$(ODIR)/calculator_test.o: $(TDIR)/calculator_test.c
	$(CC) -c $(TDIR)/calculator_test.c -o $@


############################################################################################################
#Utilities
.PHONY: clean all release debug test

clean:
	rm $(ODIR)/*.o *.out
